[package]
name = "mangastream_template"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aidoku = { git = "https://github.com/Aidoku/aidoku-rs", features = ["helpers"] }
hashbrown = "0.14.5"
